//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.08 at 02:49:05 PM CEST 
//


package hotel.tilufwlow.webservices;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for address complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="address">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded">
 *         &lt;element name="line1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="line2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="line3" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "address", propOrder = {
    "line1AndLine2AndLine3"
})
public class Address {

    @XmlElementRefs({
        @XmlElementRef(name = "line3", namespace = "http://webservices.tilufwlow.hotel", type = JAXBElement.class),
        @XmlElementRef(name = "line1", namespace = "http://webservices.tilufwlow.hotel", type = JAXBElement.class),
        @XmlElementRef(name = "line2", namespace = "http://webservices.tilufwlow.hotel", type = JAXBElement.class)
    })
    protected List<JAXBElement<String>> line1AndLine2AndLine3;

    /**
     * Gets the value of the line1AndLine2AndLine3 property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the line1AndLine2AndLine3 property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLine1AndLine2AndLine3().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * 
     */
    public List<JAXBElement<String>> getLine1AndLine2AndLine3() {
        if (line1AndLine2AndLine3 == null) {
            line1AndLine2AndLine3 = new ArrayList<JAXBElement<String>>();
        }
        return this.line1AndLine2AndLine3;
    }

}
