//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.08 at 09:21:50 PM CEST 
//


package hotel.tilufwlow.webservices;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EnumHotelStatus.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="EnumHotelStatus">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="fullseason01"/>
 *     &lt;enumeration value="summer02"/>
 *     &lt;enumeration value="winter03"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "EnumHotelStatus")
@XmlEnum
public enum EnumHotelStatus {

    @XmlEnumValue("fullseason01")
    FULLSEASON_01("fullseason01"),
    @XmlEnumValue("summer02")
    SUMMER_02("summer02"),
    @XmlEnumValue("winter03")
    WINTER_03("winter03");
    private final String value;

    EnumHotelStatus(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static EnumHotelStatus fromValue(String v) {
        for (EnumHotelStatus c: EnumHotelStatus.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
